Bug fix: unable to show error message on crash

diff --git a/mic_over_mumble b/mic_over_mumble
--- a/mic_over_mumble
+++ b/mic_over_mumble
@@ -172,14 +172,14 @@ get_sink_paid () {
         take_second_column)
 
      if [ -z "$result" ]; then
-        echo "Error: Failed to find the device the script should have added." 2>&1
-        print_how_to_restart 2>&1
+        echo "Error: Failed to find the device the script should have added." 1>&2
+        print_how_to_restart 1>&2
         exit 1
     fi
 
     if [ "$(echo "$result" | wc -l)" != "1" ]; then
-        echo "Error: Multiple virtual devices found." 2>&1
-        print_how_to_restart 2>&1
+        echo "Error: Multiple virtual devices found." 1>&2
+        print_how_to_restart 1>&2
         exit 1
     fi
 
